 links:
    0: https://www.heise.de/autos/rss/news-atom.xml
    1: https://www.heise.de/rss/heiseplus-atom.xml
    2: https://www.giga.de/software/feed/
    3: https://www.theverge.com/rss/index.xml
    4:
    5:
    6:
    7:
